version: "3.9"

services:
  backend:
    build: 
      context: .
      dockerfile: './05-compose-app-nginx/Dockerfile.backend'
    networks:
      - my-net
  frontend:
    build: 
      context: .
      dockerfile: './05-compose-app-nginx/Dockerfile.frontend'
    networks:
      - my-net
  nginx:
    image: nginx
    volumes:
      - ./05-compose-app-nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - my-net
    ports:
      - "8000:80"

networks:
  my-net:
    driver: bridge