version: "3.9"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/app/
      - /app/node_modules
    ports:
      - 1337:1337
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8000:3000
