version: "3.9"

services:
  backend:
    build: ./backend
    networks:
      - my-net
  frontend:
    build: ./frontend
    networks:
      - my-net
  nginx:
    image: nginx
    volumes:
      - ./server.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - my-net
    ports:
      - 8000:80

networks:
  my-net:
    driver: bridge
