filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/application-*.log
    json.keys_under_root: true
    fields:
      environment: "development"
    fields_under_root: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

path.home: /usr/share/filebeat
path.data: /var/lib/filebeat
