version: "3.7"

services:
  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    # volumes:
    #   - "mysql_data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    container_name: mysql
    tty: true
    networks:
      - net

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
    container_name: phpmyadmin
    networks:
      - net

networks:
  net:
    driver: bridge